#!/usr/bin/env node
/**
 * api-framework 命令行工具
 * 
 * 用法:
 *   api-framework init <project-name>   创建新项目
 *   api-framework dev                   开发模式（带热重载）
 *   api-framework start                 生产模式启动
 *   api-framework generate module <name>  生成新模块
 *   api-framework generate plugin <name>  生成新插件
 */
'use strict'

const fs = require('fs')
const path = require('path')
const yargs = require('yargs')
const { hideBin } = require('yargs/helpers')
const { execSync, spawn } = require('child_process')
const chalk = require('chalk')

const PKG = require('./package.json')
const logger = require('./util/logger')

// ---- 辅助函数 ----

function getTemplatePath(...segments) {
  return path.join(__dirname, 'template', ...segments)
}

function copyTemplate(src, dest, replacements = {}) {
  let content = fs.readFileSync(src, 'utf-8')
  Object.entries(replacements).forEach(([key, value]) => {
    content = content.replace(new RegExp(`\\{${key}\\}`, 'g'), value)
  })
  fs.mkdirSync(path.dirname(dest), { recursive: true })
  fs.writeFileSync(dest, content, 'utf-8')
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }
}

// ---- 命令实现 ----

/**
 * init - 初始化新项目
 */
async function initProject(projectName) {
  const targetDir = path.resolve(process.cwd(), projectName)

  if (fs.existsSync(targetDir)) {
    console.error(chalk.red(`目录已存在: ${targetDir}`))
    process.exit(1)
  }

  console.log(chalk.cyan(`\n🐱 正在创建新项目: ${projectName}\n`))

  // 创建目录结构
  const dirs = ['module', 'plugins', 'util/encrypt', 'public', 'template']
  dirs.forEach((d) => ensureDir(path.join(targetDir, d)))

  // 复制模板文件
  const templateDir = getTemplatePath('project')
  if (fs.existsSync(templateDir)) {
    const files = fs.readdirSync(templateDir, { recursive: true })
    files.forEach((file) => {
      const src = path.join(templateDir, file)
      const dest = path.join(targetDir, file)
      if (fs.statSync(src).isFile()) {
        copyTemplate(src, dest, { projectName })
      }
    })
  }

  // 生成默认文件
  const defaultFiles = {
    'package.json': `{
  "name": "${projectName}",
  "version": "1.0.0",
  "description": "API reverse proxy project generated by api-framework",
  "type": "commonjs",
  "main": "main.js",
  "scripts": {
    "dev": "api-framework dev",
    "start": "api-framework start"
  },
  "dependencies": {
    "api-framework": "^${PKG.version}"
  }
}
`,
    '.env': `PORT=3000
HOST=0.0.0.0
LOG_LEVEL=info
ENABLE_CACHE=true
CACHE_TTL=120
`,
    'config.js': `/**
 * 项目配置文件
 * 覆盖 api-framework 的默认配置
 */
'use strict'

module.exports = {
  // 在这里覆盖框架默认配置
  // port: 3000,
  // host: '0.0.0.0',
}
`,
    'module/example.js': `/**
 * 示例 API 模块
 * 
 * 文件名自动转换为路由路径:
 *   user_login.js -> /user/login
 *   getSongUrl.js -> /get/song/url
 */
'use strict'

module.exports = async (ctx, core) => {
  const { query } = ctx
  const { request, logger } = core

  logger.info('示例模块被调用:', query)

  // 在这里调用目标 API
  // const result = await request('/target/api', { ... })

  return {
    status: 200,
    body: {
      code: 200,
      message: 'Hello from ' + ctx.path,
      data: query,
    },
  }
}
`,
  }

  Object.entries(defaultFiles).forEach(([name, content]) => {
    fs.writeFileSync(path.join(targetDir, name), content, 'utf-8')
    console.log(chalk.green(`  ✔ 创建 ${name}`))
  })

  // 创建 util/index.js
  const utilIndex = `/**
 * 项目工具函数
 * 在这里添加你的辅助函数
 */
'use strict'

module.exports = {
  // 你的工具函数...
}
`
  fs.writeFileSync(path.join(targetDir, 'util', 'index.js'), utilIndex, 'utf-8')
  console.log(chalk.green(`  ✔ 创建 util/index.js`))

  // 安装依赖
  console.log(chalk.cyan('\n📦 正在安装依赖...\n'))
  try {
    execSync('npm install', { cwd: targetDir, stdio: 'inherit' })
    console.log(chalk.green('\n✅ 项目初始化完成！\n'))
    console.log(chalk.cyan(`   cd ${projectName}`))
    console.log(chalk.cyan('   npm run dev\n'))
  } catch (err) {
    console.warn(chalk.yellow('\n⚠️  依赖安装失败，请手动执行 npm install\n'))
  }
}

/**
 * dev - 开发模式
 */
async function devMode() {
  console.log(chalk.cyan('\n🐱 开发模式启动中...\n'))

  // 尝试使用 nodemon
  try {
    const nodemonPath = require.resolve('nodemon/bin/nodemon.js')
    const child = spawn(
      process.execPath,
      [nodemonPath, '--watch', 'module', '--watch', 'plugins', '--watch', 'config.js', '--ext', 'js,json', 'app.js'],
      {
        stdio: 'inherit',
        cwd: process.cwd(),
      },
    )
    child.on('exit', (code) => process.exit(code))
  } catch {
    // 没有 nodemon，使用 node
    console.log(chalk.yellow('提示: 安装 nodemon 以获得热重载功能 (npm install nodemon --save-dev)'))
    const child = spawn(process.execPath, ['app.js'], {
      stdio: 'inherit',
      cwd: process.cwd(),
    })
    child.on('exit', (code) => process.exit(code))
  }
}

/**
 * start - 生产模式
 */
async function startMode() {
  console.log(chalk.cyan('\n🐱 生产模式启动中...\n'))

  const child = spawn(process.execPath, ['app.js'], {
    stdio: 'inherit',
    cwd: process.cwd(),
  })
  child.on('exit', (code) => process.exit(code))
}

/**
 * generate - 生成器
 */
async function generate(type, name) {
  const cwd = process.cwd()

  switch (type) {
    case 'module': {
      if (!name) {
        console.error(chalk.red('请指定模块名称'))
        process.exit(1)
      }
      const filePath = path.join(cwd, 'module', `${name}.js`)
      if (fs.existsSync(filePath)) {
        console.error(chalk.red(`模块已存在: ${name}.js`))
        process.exit(1)
      }
      copyTemplate(getTemplatePath('module-template.js'), filePath, { name })
      console.log(chalk.green(`✔ 模块已创建: module/${name}.js`))
      break
    }

    case 'plugin': {
      if (!name) {
        console.error(chalk.red('请指定插件名称'))
        process.exit(1)
      }
      const filePath = path.join(cwd, 'plugins', `${name}.js`)
      if (fs.existsSync(filePath)) {
        console.error(chalk.red(`插件已存在: ${name}.js`))
        process.exit(1)
      }
      const pluginContent = `/**
 * ${name} 插件
 */
'use strict'

module.exports = {
  name: '${name}',

  beforeServer: async ({ app, config }) => {
    // 服务器启动前逻辑
  },

  afterRoutes: async ({ app, config }) => {
    // 路由注册完成后逻辑
  },

  beforeRequest: async ({ req, res, module }) => {
    // 请求处理前逻辑
  },

  afterRequest: async ({ req, res, module, result }) => {
    // 请求处理后逻辑
  },

  onError: async ({ req, res, module, error }) => {
    // 错误处理逻辑
  },
}
`
      fs.writeFileSync(filePath, pluginContent, 'utf-8')
      console.log(chalk.green(`✔ 插件已创建: plugins/${name}.js`))
      break
    }

    default:
      console.error(chalk.red(`未知类型: ${type}，可用类型: module, plugin`))
      process.exit(1)
  }
}

// ---- CLI 入口 ----

async function main() {
  yargs(hideBin(process.argv))
    .scriptName('api-framework')
    .version(PKG.version)
    .usage('$0 <command> [options]')
    .command(
      'init <project-name>',
      '创建一个新的 API 项目',
      (yargs) => {
        yargs.positional('project-name', {
          describe: '项目名称',
          type: 'string',
        })
      },
      (argv) => initProject(argv['project-name']),
    )
    .command(
      'dev',
      '启动开发模式（带热重载）',
      () => {},
      () => devMode(),
    )
    .command(
      'start',
      '启动生产模式',
      () => {},
      () => startMode(),
    )
    .command(
      'generate <type> <name>',
      '生成模块或插件',
      (yargs) => {
        yargs
          .positional('type', {
            describe: '生成类型 (module|plugin)',
            type: 'string',
            choices: ['module', 'plugin'],
          })
          .positional('name', {
            describe: '名称',
            type: 'string',
          })
      },
      (argv) => generate(argv.type, argv.name),
    )
    .demandCommand(1, '请指定一个命令')
    .help()
    .strict().argv
}

main().catch((err) => {
  console.error(chalk.red('发生错误:'), err.message)
  process.exit(1)
})
