#!/usr/bin/env node
/**
 * api-framework command line tool
 *
 * Usage:
 *   api-framework init <project-name>   create a new project
 *   api-framework dev                   development mode (with hot reload)
 *   api-framework start                 production mode
 *   api-framework generate module <name>  generate a new module
 *   api-framework generate plugin <name>  generate a new plugin
 */
'use strict'

const fs = require('fs')
const path = require('path')
const yargs = require('yargs')
const { hideBin } = require('yargs/helpers')
const { execSync, spawn } = require('child_process')
const chalk = require('chalk')

const PKG = require('./package.json')
const logger = require('./util/logger')

// ---- helper functions ----

function getTemplatePath(...segments) {
  return path.join(__dirname, 'template', ...segments)
}

function copyTemplate(src, dest, replacements = {}) {
  let content = fs.readFileSync(src, 'utf-8')
  Object.entries(replacements).forEach(([key, value]) => {
    content = content.replace(new RegExp(`\\{${key}\\}`, 'g'), value)
  })
  fs.mkdirSync(path.dirname(dest), { recursive: true })
  fs.writeFileSync(dest, content, 'utf-8')
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }
}

// ---- command implementations ----

/**
 * init - create a new project
 */
async function initProject(projectName) {
  const targetDir = path.resolve(process.cwd(), projectName)

  if (fs.existsSync(targetDir)) {
    console.error(chalk.red(`Directory already exists: ${targetDir}`))
    process.exit(1)
  }

  console.log(chalk.cyan(`\nCreating new project: ${projectName}\n`))

  // create directory structure
  const dirs = ['module', 'plugins', 'util/encrypt', 'public', 'template']
  dirs.forEach((d) => ensureDir(path.join(targetDir, d)))

  // copy template files
  const templateDir = getTemplatePath('project')
  if (fs.existsSync(templateDir)) {
    const files = fs.readdirSync(templateDir, { recursive: true })
    files.forEach((file) => {
      const src = path.join(templateDir, file)
      const dest = path.join(targetDir, file)
      if (fs.statSync(src).isFile()) {
        copyTemplate(src, dest, { projectName })
      }
    })
  }

  // generate default files
  const defaultFiles = {
    'package.json': `{
  "name": "${projectName}",
  "version": "1.0.0",
  "description": "API reverse proxy project generated by api-framework",
  "type": "commonjs",
  "main": "main.js",
  "scripts": {
    "dev": "api-framework dev",
    "start": "api-framework start"
  },
  "dependencies": {
    "api-framework": "^${PKG.version}"
  }
}
`,
    '.env': `PORT=3000
HOST=0.0.0.0
LOG_LEVEL=info
ENABLE_CACHE=true
CACHE_TTL=120
`,
    'config.js': `/**
 * Project configuration
 * Overrides api-framework default config
 */
'use strict'

module.exports = {
  // override framework defaults here
  // port: 3000,
  // host: '0.0.0.0',
}
`,
    'module/example.js': `/**
 * Example API module
 *
 * File name is auto-converted to route path:
 *   user_login.js -> /user/login
 *   getSongUrl.js -> /get/song/url
 */
'use strict'

module.exports = async (ctx, core) => {
  const { query } = ctx
  const { request, logger } = core

  logger.info('Example module called:', query)

  // call target API here
  // const result = await request('/target/api', { ... })

  return {
    status: 200,
    body: {
      code: 200,
      message: 'Hello from ' + ctx.path,
      data: query,
    },
  }
}
`,
  }

  Object.entries(defaultFiles).forEach(([name, content]) => {
    fs.writeFileSync(path.join(targetDir, name), content, 'utf-8')
    console.log(chalk.green(`  + created ${name}`))
  })

  // create util/index.js
  const utilIndex = `/**
 * Project utility functions
 * Add your helper functions here
 */
'use strict'

module.exports = {
  // your utility functions...
}
`
  fs.writeFileSync(path.join(targetDir, 'util', 'index.js'), utilIndex, 'utf-8')
  console.log(chalk.green(`  + created util/index.js`))

  // install dependencies
  console.log(chalk.cyan('\nInstalling dependencies...\n'))
  try {
    execSync('npm install', { cwd: targetDir, stdio: 'inherit' })
    console.log(chalk.green('\nProject initialization complete!\n'))
    console.log(chalk.cyan(`   cd ${projectName}`))
    console.log(chalk.cyan('   npm run dev\n'))
  } catch (err) {
    console.warn(chalk.yellow('\nDependency installation failed, please run npm install manually\n'))
  }
}

/**
 * dev - development mode
 */
async function devMode() {
  console.log(chalk.cyan('\nStarting development mode...\n'))

  // try to use nodemon
  try {
    const nodemonPath = require.resolve('nodemon/bin/nodemon.js')
    const child = spawn(
      process.execPath,
      [nodemonPath, '--watch', 'module', '--watch', 'plugins', '--watch', 'config.js', '--ext', 'js,json', 'app.js'],
      {
        stdio: 'inherit',
        cwd: process.cwd(),
      },
    )
    child.on('exit', (code) => process.exit(code))
  } catch {
    // no nodemon, use plain node
    console.log(chalk.yellow('Tip: install nodemon for hot reload (npm install nodemon --save-dev)'))
    const child = spawn(process.execPath, ['app.js'], {
      stdio: 'inherit',
      cwd: process.cwd(),
    })
    child.on('exit', (code) => process.exit(code))
  }
}

/**
 * start - production mode
 */
async function startMode() {
  console.log(chalk.cyan('\nStarting production mode...\n'))

  const child = spawn(process.execPath, ['app.js'], {
    stdio: 'inherit',
    cwd: process.cwd(),
  })
  child.on('exit', (code) => process.exit(code))
}

/**
 * generate - generator
 */
async function generate(type, name) {
  const cwd = process.cwd()

  switch (type) {
    case 'module': {
      if (!name) {
        console.error(chalk.red('Please specify a module name'))
        process.exit(1)
      }
      const filePath = path.join(cwd, 'module', `${name}.js`)
      if (fs.existsSync(filePath)) {
        console.error(chalk.red(`Module already exists: ${name}.js`))
        process.exit(1)
      }
      copyTemplate(getTemplatePath('module-template.js'), filePath, { name })
      console.log(chalk.green(`+ created module: ${name}.js`))
      break
    }

    case 'plugin': {
      if (!name) {
        console.error(chalk.red('Please specify a plugin name'))
        process.exit(1)
      }
      const filePath = path.join(cwd, 'plugins', `${name}.js`)
      if (fs.existsSync(filePath)) {
        console.error(chalk.red(`Plugin already exists: ${name}.js`))
        process.exit(1)
      }
      const pluginContent = `/**
 * ${name} plugin
 */
'use strict'

module.exports = {
  name: '${name}',

  beforeServer: async ({ app, config }) => {
    // logic before server starts
  },

  afterRoutes: async ({ app, config }) => {
    // logic after routes are registered
  },

  beforeRequest: async ({ req, res, module }) => {
    // logic before each request
  },

  afterRequest: async ({ req, res, module, result }) => {
    // logic after each request
  },

  onError: async ({ req, res, module, error }) => {
    // error handling logic
  },
}
`
      fs.writeFileSync(filePath, pluginContent, 'utf-8')
      console.log(chalk.green(`+ created plugin: ${name}.js`))
      break
    }

    default:
      console.error(chalk.red(`Unknown type: ${type}, available types: module, plugin`))
      process.exit(1)
  }
}

// ---- CLI entry ----

async function main() {
  yargs(hideBin(process.argv))
    .scriptName('api-framework')
    .version(PKG.version)
    .usage('$0 <command> [options]')
    .command(
      'init <project-name>',
      'Create a new API project',
      (yargs) => {
        yargs.positional('project-name', {
          describe: 'Project name',
          type: 'string',
        })
      },
      (argv) => initProject(argv['project-name']),
    )
    .command(
      'dev',
      'Start development mode (with hot reload)',
      () => {},
      () => devMode(),
    )
    .command(
      'start',
      'Start production mode',
      () => {},
      () => startMode(),
    )
    .command(
      'generate <type> <name>',
      'Generate a module or plugin',
      (yargs) => {
        yargs
          .positional('type', {
            describe: 'Generation type (module|plugin)',
            type: 'string',
            choices: ['module', 'plugin'],
          })
          .positional('name', {
            describe: 'Name',
            type: 'string',
          })
      },
      (argv) => generate(argv.type, argv.name),
    )
    .demandCommand(1, 'Please specify a command')
    .help()
    .strict().argv
}

main().catch((err) => {
  console.error(chalk.red('Error:'), err.message)
  process.exit(1)
})
